### ISSUE TITLE
Think about removing the usages or publishing the sources of the Prime.Arbitrage package, if necessary

### ISSUE THREAD

**Issue by dotWee** [hitchhiker/prime#1]
While opening the prime source in Visual Studio for Mac, the following issues occurred:

![](https://i.imgur.com/1F2G5LI.png)

The main Prime solution references a external package with the path _..\prv\Prime.Arbitrage_, of which the sources neither are available nor included in the repository.

https://github.com/hitchhiker/prime/blob/b6169ac412504a5868abe3493bbd06dab87e8b08/Prime.sln#L42

This may should be removed or fixed, if the Prime project depends on them.

I'm aware that prime is currently in pre-alpha state, but i think its necessary to solve this issue to match its open-source philosophy.

**Comment by hitchhiker** [comment]
Yeah, we are looking to do a full cleanup soon - there's a lot of junk / attempts / discovery code in there..
Thanks @dotWee
