### ISSUE TITLE
Remove .NETFramework API usages to support more platforms

### ISSUE THREAD

**Issue by dotWee** [hitchhiker/prime#2]
Building the main Prime solution with Visual Studio for Mac currently fails at the following error:

> /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(5,5): Error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.7.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. (MSB3644) (Prime.Spark)

This is caused by a missing support of the .NETFramework v4.7.1 on the MacOS (as well as Linux) platform. To get Prime running on more platforms, its suggested to remove .NETFramework v4.7.1 API usages and / or implement cross-platform solutions (like [Mono](http://www.mono-project.com/), the cross platform and open source .NET framework) as replacement.

![dotnetframework](https://user-images.githubusercontent.com/8060356/34696043-858e6c42-f4cd-11e7-80c5-4a09250395fe.png)

**Comment by hitchhiker** [comment]
Only the WPF UI requires 4.7.1, the satellite / core projects run on .NET STANDARD.. The project layout is still messy and will need a full cleanup soon.
The main part of the project (core) has been tested and runs on Linux/.NET CORE though..

**Comment by hitchhiker** [comment]
I sent an update to include two solution files (better solution later) -> one for WIN and one for .NET Core..
Not much you can do with the project at this point (unless you are directly using the providers) as it's headless on anything but WIN for now.

**Comment by dotWee** [comment]
Can confirm, the solution [Prime-core](https://github.com/hitchhiker/prime/blob/master/Prime-core.sln) builds error-free on both Mac and Linux. Thank you for the patch!

I don't have much experience when it comes to the .NET framework, but I'll fork the source and try to get it running on my Mac.

**Comment by hitchhiker** [comment]
glad to hear @dotWee - but again, no UI for anything other than WIN at the moment. Very alpha state, it's only 6 months into development. Basically for now it's a set of APIs. We're looking to implement Electron shortly.
