### ISSUE TITLE
Crashes on Launch

### ISSUE THREAD

**Issue by whiteneutron** [hitchhiker/prime#7]
I installed the app on two separate computers.
Both are currently up-to-date, but Prime crashes on launch.
I downloaded the Google Drive version on getprime

**Comment by hitchhiker** [comment]
Hey @whiteneutron - yep, we see the same on this end. That was a very early ALPHA test, i'll remove the links now. I'll ping you back when we get a more stable version for release.

**Comment by whiteneutron** [comment]
I managed to get the console running and the IPFS webUI
Daemon is ready and I have the DNS hash
Is part of application accessible at this point?

**Comment by hitchhiker** [comment]
Hey WN, thanks for your interest. We haven't been working on the UI in some time, I believe there are issues with it. I'll dedicate some time to it as soon as possible and see if I can get an updated version that might allow you to make some use of it. What functionality is most useful to you for now? (I'll try to push any usable core code to the UI for you)

**Comment by hitchhiker** [comment]
re: Slack -> Can you see anything public here: https://getprime.slack.com
