### ISSUE TITLE
Logotype for the project

### ISSUE THREAD

**Issue by nunojesus** [hitchhiker/prime#8]
Hi, I like to contribute with graphic designs, in opensource projects, so if you need something from me like a logotype or something else just say it, Im here ready to help you.
Greetings!
Nuno Jesus

**Comment by hitchhiker** [comment]
Wow Nuno,

Thanks man, that's just so awesome!! :D We're up to our necks in coding right now, as soon as we're anywhere near UI I'll ping you back? 

I love open source! You made my day man,
Frank.
